### ISSUE TITLE
Some questions about the experiment setting in the TABLE1.

### ISSUE THREAD

**Issue by KQL11** [SummerMVP/TStegNet#1]
Hello! 
I'm grateful for your code, and I think the "TStegNet" is a really nice work! However, after reading the article, I still have some questions about the experiment setting. 

1. Why the performance in S-UNIWARD of DengNet is far lower than the performance in original paper in table 1? (Actually, I also get a better result like 89% ACC in S-UNIWARD 0.4 through running your code)
 
2. How do you attack the models to generate adversarial examples? (I want to know the details of the pipeline. For example, do the attack targets include the "Gradient Generator"? Or do the attackers know about the operation of permuting images and the existence of gradient subnet?)
 
3. What is the meaning of "DengNet was used as the target model for attack ..." in page 3? In my understanding, it looks as if the attackers will only use the gradient information from DengNet, where DengNet is just a gradient generator.

4. If the viewpoint of question 3 is correct, were the results of your paper generate by the joint prediction of DengNet and TStegNet? For example, the input image will input to the DengNet and if the output of DengNet is 0, then the input image will be tested in TStegNet again.

In the end, I appreciate the paper and the code once more.

**Comment by SummerMVP** [comment]
1.请问你是在测试集计算的准确率吗？我在验证集上也达到了89%的准确率，但是表格1中记录的是测试集的ACC，确实是比原论文的效果差。如果你在test set中也达到了89%的准确率那我就不知道原因了，也许是因为我们数据集的划分方式不同。
2.攻击目标就是作为梯度生成器的DengNet。具体的攻击过程就是论文中两种对抗隐写方法的复现。攻击者并不知道梯度子网的存在和图像置乱的存在。也许你可以看看那两篇论文的具体内容，这对攻击过程的理解非常有帮助。
3.DengNet也是一种隐写分析器，进行训练后可检测隐写图片，这里使用的损失函数是原论文所使用的。在TStegNet中，通过置信度损失函数可以获得输入图片的梯度信息，因此在这里作为梯度生成器，没有隐写分析的功能。"DengNet was used as the target model for attack ..."，生成对抗隐写图片时需要有个目标网络，这是对数据集的生成进行说明，和TStegNet的架构无关。事实上，TStegNet也可以使用其他隐写分析网络作为梯度生成器。
4.DengNet提供了梯度信息，梯度信息进行特征处理后参与分类，它属于TStegNet的一部分，并不是联合预测。
你是Zhang WeiMing老师的学生吗？如果都是中国人就直接用中文交流吧！祝好！


从 Windows 版邮件发送

发件人: Lin Kaiqing
发送时间: 2023年9月27日 21:53
收件人: SummerMVP/TStegNet
抄送: Subscribed
主题: [SummerMVP/TStegNet] Some questions about the experiment setting inthe TABLE1. (Issue #1)

Hello!
I'm grateful for your code, and I think the "TStegNet" is a really nice work! However, after reading the article, I still have some questions about the experiment setting.
1. Why the performance in S-UNIWARD of DengNet is far lower than the performance in original paper in table 1? (Actually, I also get a better result like 89% ACC in S-UNIWARD 0.4 through running your code)
2. How do you attack the models to generate adversarial examples? (I want to know the details of the pipeline. For example, do the attack targets include the "Gradient Generator"? Or do the attackers know about the operation of permuting images and the existence of gradient subnet?)
3. What is the meaning of "DengNet was used as the target model for attack ..." in page 3? In my understanding, it looks as if the attackers will only use the gradient information from DengNet, where DengNet is just a gradient generator.
4. If the viewpoint of question 3 is correct, were the results of your paper generate by the joint prediction of DengNet and TStegNet? For example, the input image will input to the DengNet and if the output of DengNet is 0, then the input image will be tested in TStegNet again.
In the end, I appreciate the paper and the code once more.

**Comment by KQL11** [comment]
非常感谢你的回答！我是深圳大学Bin Li老师的学生。
我还有一个疑虑，在攻击者已知全部的模型设置的情况下（包括图像置乱和梯度子网络），TStegNet的抗攻击能力可能会相对差一些，你认为这是正常且合理的吗？这并不是说你的方法不优秀，而是因为我的一些实验可能需要对比TStegNet，因此想向你这边确认一下。
祝好！

**Comment by SummerMVP** [comment]
如果已知所有的模型设置的话，可以进行针对性的对抗攻击，抗攻击能力肯定会相对差一些的。李斌老师的团队也非常优秀！有机会欢迎多多交流！发自我的 iPhone在 2023年9月28日，20:13，Lin Kaiqing ***@***.***> 写道：﻿
非常感谢你的回答！我是深圳大学Bin Li老师的学生。
我还有一个疑虑，在攻击者已知全部的模型设置的情况下（包括图像置乱和梯度子网络），TStegNet的抗攻击能力可能会相对差一些，你认为这是正常且合理的吗？这并不是说你的方法不优秀，而是因为我的一些实验可能需要对比TStegNet，因此想向你这边确认一下。
祝好！

**Comment by KQL11** [comment]
感谢！2100432033@email.szu.edu.cn，这是我的邮箱，希望未来多多交流！
